const DICTIONARY = {
    en: {
        MENU_TITLE: "MENU",
        PLAY_GAME_PVP: "Play Game (Player vs Player)",
        PLAY_GAME_PVC: "Play Game (Player vs Computer)",
        SETTINGS: "Settings",
        EXIT_GAME: "Exit Game",
        SETTINGS_TITLE: "SETTINGS",
        LANGUAGE_SETTING: "Change Language",
        RETURN_TO_MENU: "Return to Menu",
        CHOOSE_LANGUAGE: "Choose Language",
        LANGUAGE_CHANGED: "Language has been changed.",
        PRESS_ENTER_TO_CONTINUE: "Press Enter to continue...",
        PLAY_AGAIN_QUESTION: "Do you want to play again? (y/n)",
        DRAW_GAME: "It's a draw!",
        WINNER_IS: "The winner is",
        PLAYER: "Player",
        PLAYER_ONE: "one",
        PLAYER_TWO: "two",
        PLAYER_TURN: "Player's turn: ",
        GAME_OVER: "GAME OVER",
        PLACE_YOUR_MARK: "Place your mark at: ",
        INVALID_INPUT: "Invalid input. Please enter two numbers between 1 and 3 for a valid position.",
        COMPUTER_TURN: "Computer's turn...",
        HUMAN_PLAYER: "Human",
        COMPUTER_PLAYER: "Computer"
    },
    nl: {
        MENU_TITLE: "MENU",
        PLAY_GAME_PVP: "Speel Spel (Speler tegen Speler)",
        PLAY_GAME_PVC: "Speel Spel (Speler tegen Computer)",
        SETTINGS: "Instellingen",
        EXIT_GAME: "Stop Spel",
        SETTINGS_TITLE: "INSTELLINGEN",
        LANGUAGE_SETTING: "Verander Taal",
        RETURN_TO_MENU: "Terug naar Menu",
        CHOOSE_LANGUAGE: "Kies Taal",
        LANGUAGE_CHANGED: "De taal is gewijzigd.",
        PRESS_ENTER_TO_CONTINUE: "Druk op Enter om door te gaan...",
        PLAY_AGAIN_QUESTION: "Wil je opnieuw spelen? (j/n)",
        DRAW_GAME: "Het is een gelijkspel!",
        WINNER_IS: "De winnaar is",
        PLAYER: "Speler",
        PLAYER_ONE: "een",
        PLAYER_TWO: "twee",
        PLAYER_TURN: "Beurt van speler: ",
        GAME_OVER: "SPEL AFGELOPEN",
        PLACE_YOUR_MARK: "Plaats je markering op: ",
        INVALID_INPUT: "Ongeldige invoer. Voer twee cijfers in tussen 1 en 3 voor een geldige positie.",
        COMPUTER_TURN: "Beurt van de computer...",
        HUMAN_PLAYER: "Mens",
        COMPUTER_PLAYER: "Computer"
    }
};

export default DICTIONARY;