const DICTIONARY = {
    en: {
        MENU_TITLE: "Main Menu",
        PLAY_GAME_PVP: "PVP (Player vs Player)",
        PLAY_GAME_PVC: "PVC (Player vs Computer)",
        SETTINGS: "Settings",
        EXIT_GAME: "Exit Game",
        LANGUAGE_SETTING: "Change Language",
        RETURN_TO_MENU: "Return to Menu",
        CHOOSE_LANGUAGE: "Choose your language:",
        LANGUAGE_CHANGED: "Language changed!",
        PRESS_ENTER_TO_CONTINUE: "Press Enter to continue...",
        PLAYER_ONE: "Player 1",
        PLAYER_TWO: "Player 2",
        PLAYER_TURN: "It's your turn:",
        PLACE_YOUR_MARK: "Place your mark (row col):",
        INVALID_INPUT: "Invalid input, please try again.",
        PLAY_AGAIN_QUESTION: "Do you want to play again? (yes/no)",
        DRAW_GAME: "It's a draw!",
        WINNER_IS: "The winner is",
        HUMAN_PLAYER: "Human",
        COMPUTER_PLAYER: "Computer",
        GAME_OVER: "GAME OVER",
        COMPUTER_TURN: "Computer's turn..."
    },
    nl: {
        MENU_TITLE: "Hoofdmenu",
        PLAY_GAME_PVP: "PTP (Speler tegen Speler)",
        PLAY_GAME_PVC: "PTC (Speler tegen Computer)",
        SETTINGS: "Instellingen",
        EXIT_GAME: "Spel Afsluiten",
        LANGUAGE_SETTING: "Taal Wijzigen",
        RETURN_TO_MENU: "Terug naar menu",
        CHOOSE_LANGUAGE: "Kies je taal:",
        LANGUAGE_CHANGED: "Taal is gewijzigd!",
        PRESS_ENTER_TO_CONTINUE: "Druk op Enter om door te gaan...",
        PLAYER_ONE: "Speler 1",
        PLAYER_TWO: "Speler 2",
        PLAYER_TURN: "Het is jouw beurt:",
        PLACE_YOUR_MARK: "Plaats je markering (rij kolom):",
        INVALID_INPUT: "Ongeldige invoer, probeer het opnieuw.",
        PLAY_AGAIN_QUESTION: "Wil je opnieuw spelen? (ja/nee)",
        DRAW_GAME: "Het is een gelijkspel!",
        WINNER_IS: "De winnaar is",
        HUMAN_PLAYER: "Mens",
        COMPUTER_PLAYER: "Computer",
        GAME_OVER: "SPEL AFGELOPEN",
        COMPUTER_TURN: "Beurt van de computer..."
    }
};

export default DICTIONARY;
